import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.sql.ResultSetMetaData;
//import java.util.*;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.concurrent.*;

public class ConcurrentAlignment {
	
    private static String dbURL;
    private static String tableName = "dnaseqs.testtable1";//"dnaseqs.realtable2";
    // jdbc Connection
    public static Connection conn = null;
    
    public static Statement stmt = null;
    
    public static ResultSet results;
    
    public static String test1 = "ATACGTCTA";
    public static String target = "ATCGATCAA";//GGATCTCGATACGATCGAC";//TAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGG";//AGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTACATCGATCAAGGATCTCGATACGATCGACTAGCTACGACTACATTTACGATCTAGGAGGCCCTAGATCGATCAGCTACGACTAC";
    
    
    public static CleanLazyList finalResults= new CleanLazyList();
//    public static AlignResult testResult;
    
    public int me;
    public static Lock lock = new ReentrantLock();


	public ConcurrentAlignment(int newMe) {
		me = newMe;
	}
	
	
	public static void main(String[] args){
		
        String os = System.getProperty("os.name");
        if (os.startsWith("Linux")){
            dbURL = "jdbc:derby:../MyDB;";
        }
        else{
            dbURL = "jdbc:derby:MyDB;";
        }
        createConnection();
        
        try {
			stmt = conn.createStatement();
		} catch (SQLException e2) {
			e2.printStackTrace();
		}
        
		try {
			ResultSet results = stmt.executeQuery("select * from " + tableName);
			BlockingQueue<DbResult> queue1 = new LinkedBlockingQueue<DbResult>(10);
	        Producer producer = new Producer(queue1, results);
	        //Splitter splitter = new Splitter(queue1, target);
	        
	        Thread p1 = new Thread(producer);
//	        Thread p2 = new Thread(producer);
	        Thread c1 = new Thread(new Splitter(queue1, target));
	        Thread c2 = new Thread(new Splitter(queue1, target));
	        
	        p1.start();
//	        p2.start();
	        c1.start();
	        //c2.start();
	        
	        try{
	        	p1.join();
//	        	p2.join();
	        	c1.join();
	        	//c2.join();
	        } catch(InterruptedException e) {}
	        
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
        
        
        
//        Thread t1 = new Thread(new ConcurrentAlignment(1));
//        Thread t2 = new Thread(new ConcurrentAlignment(2));
//        
//        try{
//            stmt = conn.createStatement();
//            results = stmt.executeQuery("select * from " + tableName);
//        }
//        catch (SQLException sqlExcept){
//            sqlExcept.printStackTrace();
//        }
//    
//        t1.start();
//        t2.start();
//        try{
//            t1.join();
//            t2.join();
//        } 
//        catch (InterruptedException e) {}
           
        try{
            //results.close();
            stmt.close();
        }
        catch (SQLException sqlExcept){
            sqlExcept.printStackTrace();
        }
        
		shutdown();
	}
	private static void createConnection()
    {
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
            //Get a connection
            conn = DriverManager.getConnection(dbURL); 
        }
        catch (Exception except){
            except.printStackTrace();
        }
   }
   
    private static void shutdown()
    {
        try{
            if (stmt != null){
                stmt.close();
            }
            if (conn != null){
                DriverManager.getConnection(dbURL + ";shutdown=true");
                conn.close();
            }           
        }
        catch (SQLException sqlExcept){
        	// This will always happen, so we don't need to print anything, really 
            //sqlExcept.printStackTrace();
        }
    }
	
}
