import java.util.*;

public class SequentialAlignment {
	
	public SequentialAlignment() {
		
	}
	// Original input sequences
	private static char[] sequence1;
	private static char[] sequence2;

	// Constructed aligned sequences
	public static ArrayList<Character> gappedSeq1 = new ArrayList<Character>();
	public static ArrayList<Character> gappedSeq2 = new ArrayList<Character>();
	
	// Score variables
	public static int matchScore;
	public static int startGaps;
	public static int continueGaps;
	
	
	public static int[][] ConstructArray(String seq1, String seq2) {
		/*		
		 * 			0	S	e	q	2
		 * 			-	-	-	-	-
		 * 	 0	| 	0	0	0	0	0
		 * 	 S	| 	0	x	x	x	x
		 * 	 e	| 	0	x	x	x	x
		 * 	 q	| 	0	x	x	x	x
		 * 	 1	| 	0	x	x	x	x
		 * 
		 */
			
		
		sequence1 = seq1.toCharArray();
		sequence2 = seq2.toCharArray();
		
		// If sequences are too long 2d array will be too large
		//		---> Return early
		if (((sequence1.length+1) * (sequence2.length+1)) == Integer.MAX_VALUE || ((sequence1.length+1) * (sequence2.length+1))<=0) {
			int [][] emptyArray = new int[0][0];
			return emptyArray;
		}	
		
		// Otherwise, proceed as usual
		int [][] ourArray = new int[sequence1.length + 1][sequence2.length +1];
		int [][] backtraceArray = new int[sequence1.length + 1][sequence2.length +1];
		
		for(int i=1; i < sequence1.length + 1; i++)
		{
			for(int j=1; j < sequence2.length + 1; j++)
			{
				int matchMax = Math.max(Math.max(ourArray[i-1][j], ourArray[i][j-1]), 1+ ourArray[i-1][j-1]);
				int mismatchMax = Math.max(ourArray[i-1][j], ourArray[i][j-1]);
				// MATCH
				if(sequence1[i-1] == sequence2[j-1])
				{
					ourArray[i][j] = matchMax;
					
					//BackTrace
					if (matchMax == 1+ ourArray[i-1][j-1])
					{
						// 3 = Trace from the diagonal
						backtraceArray[i][j] = 3;
					} else if (matchMax == ourArray[i][j-1]) {
						// 2 = Trace from the left
						// AKA Gap in Seq2
						backtraceArray[i][j] = 2;
					} else {
						// 1 = Trace from the top
						// AKA Gap in Seq1
						backtraceArray[i][j] = 1;
					}
					
				// MISMATCH
				} else {
					ourArray[i][j] = mismatchMax;
					
					//BackTrace
					if (matchMax == ourArray[i][j-1]) {
						// 2 = Trace from the left
						// AKA Gap in Seq2
						backtraceArray[i][j] = 2;
					} else {
						// 1 = Trace from the top
						// AKA Gap in Seq1
						backtraceArray[i][j] = 1;
					}
				}
				
				
			}
		}
		return backtraceArray;

	}
	
	public static AlignResult getResult(int[][] backtrace, int i, int j, ArrayList<Character> gap1, ArrayList<Character> gap2){

		//Initialize scoring
		matchScore = 0;
		startGaps = 0;
		continueGaps = 0;
		
		
		while(backtrace[i][j] != 0)
		{
			if(backtrace[i][j] == 3)
			{
				// Mark traversed
				backtrace[i][j] = 6;
				
				// Increase match score
				matchScore += 5;
				
				// Create alignment
				gap1.add(0, sequence1[i-1]);
				gap2.add(0, sequence2[j-1]);
				
				// Go to next cell
				i--;
				j--;
				
			} else if (backtrace[i][j] == 2) {
				// Mark traversed
				backtrace[i][j] = 5;
				
				// Increase gap score
				if(j != sequence2.length && backtrace[i][j+1] == 5) {
					continueGaps += 1;
				} else {
					startGaps += 2;
				}
				
				// Create alignment
				gap1.add(0, '-');
				gap2.add(0, sequence2[j-1]);
				
				// Go to next cell
				j--;
				
			} else if (backtrace[i][j] == 1) {
				// Mark traversed
				backtrace[i][j] = 4;
				
				// Increase gap score
				if(i != sequence1.length && backtrace[i+1][j] == 4)
				{
					continueGaps += 1;
				} else {
					startGaps += 2;
				}
				
				// Create alignment
				gap1.add(0, sequence1[i-1]);
				gap2.add(0, '-');
				
				// Go to next cell
				i--;
			}
		}

		
		if (i>0){
			while (i>0)
			{
				gap1.add(0, sequence1[i-1]);
				gap2.add(0, '-');
				i--;
			}
		}
		
		if (j>0){
			while (j>0)
			{
				gap1.add(0, '-');
				gap2.add(0, sequence2[j-1]);
				j--;
			}
		}
		
		int finalScore = matchScore - startGaps - continueGaps;
		AlignResult result = new AlignResult(gap1, gap2, finalScore);
		System.out.println("FINAL SCORE = " + finalScore);
		return result;
	}
	
	
	
	public static void main(String[] args){
		
		// TEST
		String test1 = "abcadaccd";//abbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcaabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabcadaccdabbabca";
		String test2 = "abcdaacbad";//cbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaacbadcbcabcdaac";		
		
		int[][] testBacktrace = ConstructArray(test1, test2);
		
		// If sequences are too large
		if (testBacktrace.length == 0 ){
			System.out.println("Sequence length exceeded maximum. Alignment not computed.");
			System.out.println();
		
		// For sequences of acceptable length
		} else {
		
			AlignResult testResult = getResult(testBacktrace, sequence1.length, sequence2.length, gappedSeq1, gappedSeq2);
		
			//testArray[1][2] = 5;
			
	//		for(int i=0; i < sequence1.length + 1; i++)
	//		{
	//			for(int j=0; j < sequence2.length + 1; j++)
	//			{
	//				System.out.print(testBacktrace[i][j] + " ");
	//			}
	//			System.out.println();
	//		}
			
			//System.out.print(testBacktrace[sequence1.length][sequence2.length]);
			System.out.println();
			
			for(int i=0; i < testResult.seq1.size(); i++){
				System.out.print(testResult.seq1.get(i));
			}
			System.out.println();
			for(int i=0; i < testResult.seq2.size(); i++){
				System.out.print(testResult.seq2.get(i));
			}
			System.out.println();
			System.out.println();
			System.out.println();
			
			System.out.println(sequence1.length);
			
		}
		
		
	}
	
	
}